### ISSUE TITLE
Enhancement Idea - Performance and HTTP Call

### ISSUE THREAD

**Issue by Franklin89** [DixonDs/serilog-sinks-teams#1]
@DixonDs First off, great work :+1: 

Might be an idea to look at the [Http Sink](https://github.com/FantasticFiasco/serilog-sinks-http/blob/9ffaf4501e84af088aee9011ce9ceb541295864b/src/Serilog.Sinks.Http/Sinks/Http/Private/Sinks/HttpSink.cs) and to use a buffer and proper async call to enhance performance.

Or use this as a [base](https://github.com/serilog/serilog-sinks-periodicbatching) similar to how the [loggly](https://github.com/serilog/serilog-sinks-loggly/blob/dev/src/Serilog.Sinks.Loggly/Sinks/Loggly/LogglySink.cs) sink uses it.

**Comment by DixonDs** [comment]
Thanks, @Franklin89 , I will definitely look into it

**Comment by DixonDs** [comment]
@Franklin89 I've given it some thought, I think it would make sense to provide two sinks similarly as in https://github.com/serilog/serilog-sinks-azuretablestorage/tree/master/src/Serilog.Sinks.AzureTableStorage/Sinks/AzureTableStorage - one for batching using `PeriodicBatchingSink` and eliminating duplicate log entries and a normal one with buffering like in https://github.com/serilog/serilog-sinks-async/blob/master/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs

What do you think?

**Comment by Franklin89** [comment]
@DixonDs I have not used one of those. But I am using the sink for [seq](https://github.com/serilog/serilog-sinks-seq) a lot and it is working great. I would suggest to follow the pattern they have. Or the [slack]() sink. 

I think providing two sinks is not the best solution. Following the Seq sink which has buffering included would be the best solution. 

Just to let you know I created a fork and will create a pull request with my idea in today or tomorrow.
